defmodule PaintSchemer.Repo.Migrations.FillPaints do
  use Ecto.Migration
  alias PaintSchemer.Paints.Manufacturer
  alias PaintSchemer.Paints.PaintType
  alias PaintSchemer.Paints.Paint

  def change do
    {:ok, games_workshop} = PaintSchemer.Repo.insert(%Manufacturer{name: "Games Workshop"})
    IO.inspect games_workshop

    {:ok, normal_type} = PaintSchemer.Repo.insert(%PaintType{name: "Normal"})
    {:ok, metallic_type} = PaintSchemer.Repo.insert(%PaintType{name: "Metallic"})
    {:ok, wash_type} = PaintSchemer.Repo.insert(%PaintType{name: "Wash"})
    {:ok, technical_type} = PaintSchemer.Repo.insert(%PaintType{name: "Technical"})
    {:ok, texture_type} = PaintSchemer.Repo.insert(%PaintType{name: "Texture"})

    paints = [
      %{name: "Abaddon Black", type_id: normal_type.id, manufacturer_id: games_workshop.id, color: "231F20"},
      %{name: "Averland Sunset", type_id: normal_type.id, manufacturer_id: games_workshop.id, color: "FDB825"},
      %{name: "Balthasar Gold", type_id: metallic_type.id, manufacturer_id: games_workshop.id, color: "A47552"},
      %{name: "Bugmans Glow", type_id: normal_type.id, manufacturer_id: games_workshop.id, color: "834F44"},
      %{name: "Caledor Sky", type_id: normal_type.id, manufacturer_id: games_workshop.id, color: "396E9E"},
      %{name: "Caliban Green", type_id: normal_type.id, manufacturer_id: games_workshop.id, color: "00401F"},
      %{name: "Castellan Green", type_id: normal_type.id, manufacturer_id: games_workshop.id, color: "314821"},
      %{name: "Celestra Grey", type_id: normal_type.id, manufacturer_id: games_workshop.id, color: "90A8A8"},
      %{name: "Ceramite White", type_id: normal_type.id, manufacturer_id: games_workshop.id, color: "FFFFFF"},
      %{name: "Daemonette Hide", type_id: normal_type.id, manufacturer_id: games_workshop.id, color: "696684"},
      %{name: "Death Guard Green", type_id: normal_type.id, manufacturer_id: games_workshop.id, color: "848A66"},
      %{name: "Deathworld Forest", type_id: normal_type.id, manufacturer_id: games_workshop.id, color: "5C6730"},
      %{name: "Dryad Bark", type_id: normal_type.id, manufacturer_id: games_workshop.id, color: "33312D"},
      %{name: "Incubi Darkness", type_id: normal_type.id, manufacturer_id: games_workshop.id, color: "0B474A"},
      %{name: "Jokaero Orange", type_id: normal_type.id, manufacturer_id: games_workshop.id, color: "EE3823"},
      %{name: "Kantor Blue", type_id: normal_type.id, manufacturer_id: games_workshop.id, color: "002151"},
      %{name: "Khorne Red", type_id: normal_type.id, manufacturer_id: games_workshop.id, color: "6A0001"},
      %{name: "Leadbelcher", type_id: metallic_type.id, manufacturer_id: games_workshop.id, color: "888D8F"},
      %{name: "Macragge Blue", type_id: normal_type.id, manufacturer_id: games_workshop.id, color: "0D407F"},
      %{name: "Mechanicus Standard Grey", type_id: normal_type.id, manufacturer_id: games_workshop.id, color: "3D4B4D"},
      %{name: "Mephiston Red", type_id: normal_type.id, manufacturer_id: games_workshop.id, color: "9A1115"},
      %{name: "Mournfang Brown", type_id: normal_type.id, manufacturer_id: games_workshop.id, color: "640909"},
      %{name: "Naggaroth Night", type_id: normal_type.id, manufacturer_id: games_workshop.id, color: "3D3354"},
      %{name: "Rakarth Flesh", type_id: normal_type.id, manufacturer_id: games_workshop.id, color: "A29E91"},
      %{name: "Ratskin Flesh", type_id: normal_type.id, manufacturer_id: games_workshop.id, color: "AD6B4C"},
      %{name: "Retributor Armour", type_id: metallic_type.id, manufacturer_id: games_workshop.id, color: "C39E81"},
      %{name: "Rhinox Hide", type_id: normal_type.id, manufacturer_id: games_workshop.id, color: "493435"},
      %{name: "Screamer Pink", type_id: normal_type.id, manufacturer_id: games_workshop.id, color: "7C1645"},
      %{name: "Screaming Bell", type_id: metallic_type.id, manufacturer_id: games_workshop.id, color: "C16F45"},
      %{name: "Steel Legion Drab", type_id: normal_type.id, manufacturer_id: games_workshop.id, color: "5E5134"},
      %{name: "Stegadon Scale Green", type_id: normal_type.id, manufacturer_id: games_workshop.id, color: "074863"},
      %{name: "The Fang Grey", type_id: normal_type.id, manufacturer_id: games_workshop.id, color: "436174"},
      %{name: "Thousand Sons Blue", type_id: normal_type.id, manufacturer_id: games_workshop.id, color: "18ABCC"},
      %{name: "Waaagh! Flesh", type_id: normal_type.id, manufacturer_id: games_workshop.id, color: "1F5429"},
      %{name: "Warplock Bronze", type_id: metallic_type.id, manufacturer_id: games_workshop.id, color: "927D7B"},
      %{name: "XV-88", type_id: normal_type.id, manufacturer_id: games_workshop.id, color: "72491E"},
      %{name: "Zandri Dust", type_id: normal_type.id, manufacturer_id: games_workshop.id, color: "9E915C"},
      %{name: "Administratum Grey", type_id: normal_type.id, manufacturer_id: games_workshop.id, color: "949B95"},
      %{name: "Ahriman Blue", type_id: normal_type.id, manufacturer_id: games_workshop.id, color: "1F8C9C"},
      %{name: "Alaitoc Blue", type_id: normal_type.id, manufacturer_id: games_workshop.id, color: "8E8C97"},
      %{name: "Altdorf Guard Blue", type_id: normal_type.id, manufacturer_id: games_workshop.id, color: "1F56A7"},
      %{name: "Auric Armour Gold", type_id: metallic_type.id, manufacturer_id: games_workshop.id, color: "E8BC6D"},
      %{name: "Balor Brown", type_id: normal_type.id, manufacturer_id: games_workshop.id, color: "8B5910"},
      %{name: "Baneblade Brown", type_id: normal_type.id, manufacturer_id: games_workshop.id, color: "937F6D"},
      %{name: "Bestigor Flesh", type_id: normal_type.id, manufacturer_id: games_workshop.id, color: "D38A57"},
      %{name: "Brass Scorpion", type_id: metallic_type.id, manufacturer_id: games_workshop.id, color: "B7885F"},
      %{name: "Cadian Fleshtone", type_id: normal_type.id, manufacturer_id: games_workshop.id, color: "C77958"},
      %{name: "Calgar Blue", type_id: normal_type.id, manufacturer_id: games_workshop.id, color: "4272B8"},
      %{name: "Dark Reaper", type_id: normal_type.id, manufacturer_id: games_workshop.id, color: "3B5150"},
      %{name: "Dawnstone", type_id: normal_type.id, manufacturer_id: games_workshop.id, color: "70756E"},
      %{name: "Deathclaw Brown", type_id: normal_type.id, manufacturer_id: games_workshop.id, color: "B36853"},
      %{name: "Doombull Brown", type_id: normal_type.id, manufacturer_id: games_workshop.id, color: "5D0009"},
      %{name: "Elysian Green", type_id: normal_type.id, manufacturer_id: games_workshop.id, color: "748F39"},
      %{name: "Emperors Children", type_id: normal_type.id, manufacturer_id: games_workshop.id, color: "B94278"},
      %{name: "Eshin Grey", type_id: normal_type.id, manufacturer_id: games_workshop.id, color: "4A4F52"},
      %{name: "Evil Sunz Scarlet", type_id: normal_type.id, manufacturer_id: games_workshop.id, color: "C2191F"},
      %{name: "Fenrisian Grey", type_id: normal_type.id, manufacturer_id: games_workshop.id, color: "719BB7"},
      %{name: "Fire Dragon Bright", type_id: normal_type.id, manufacturer_id: games_workshop.id, color: "F58652"},
      %{name: "Flash Gitz Yellow", type_id: normal_type.id, manufacturer_id: games_workshop.id, color: "FFF200"},
      %{name: "Flayed One Flesh", type_id: normal_type.id, manufacturer_id: games_workshop.id, color: "FCFCDE"},
      %{name: "Fulgurite Copper", type_id: metallic_type.id, manufacturer_id: games_workshop.id, color: "FCFCDE"},
      %{name: "Gehennas Gold", type_id: metallic_type.id, manufacturer_id: games_workshop.id, color: "DBA674"},
      %{name: "Genestealer Purple", type_id: normal_type.id, manufacturer_id: games_workshop.id, color: "7761AB"},
      %{name: "Gorthor Brown", type_id: normal_type.id, manufacturer_id: games_workshop.id, color: "654741"},
      %{name: "Hashut Copper", type_id: metallic_type.id, manufacturer_id: games_workshop.id, color: "B77647"},
      %{name: "Hoeth Blue", type_id: normal_type.id, manufacturer_id: games_workshop.id, color: "4C7FB4"},
      %{name: "Ironbreaker", type_id: metallic_type.id, manufacturer_id: games_workshop.id, color: "A1A6A9"},
      %{name: "Kabalite Green", type_id: normal_type.id, manufacturer_id: games_workshop.id, color: "038C67"},
      %{name: "Karak Stone", type_id: normal_type.id, manufacturer_id: games_workshop.id, color: "BB9662"},
      %{name: "Kislev Flesh", type_id: normal_type.id, manufacturer_id: games_workshop.id, color: "D6A875"},
      %{name: "Liberator Gold", type_id: metallic_type.id, manufacturer_id: games_workshop.id, color: "D3B587"},
      %{name: "Loren Forest", type_id: normal_type.id, manufacturer_id: games_workshop.id, color: "50702D"},
      %{name: "Lothern Blue", type_id: normal_type.id, manufacturer_id: games_workshop.id, color: "34A2CF"},
      %{name: "Moot Green", type_id: normal_type.id, manufacturer_id: games_workshop.id, color: "52B244"},
      %{name: "Nurgling Green", type_id: normal_type.id, manufacturer_id: games_workshop.id, color: "849C63"},
      %{name: "Ogryn Camo", type_id: normal_type.id, manufacturer_id: games_workshop.id, color: "9DA94B"},
      %{name: "Pallid Wych Flesh", type_id: normal_type.id, manufacturer_id: games_workshop.id, color: "CDCEBE"},
      %{name: "Pink Horror", type_id: normal_type.id, manufacturer_id: games_workshop.id, color: "90305D"},
      %{name: "Runefang Steel", type_id: metallic_type.id, manufacturer_id: games_workshop.id, color: "C3CACE"},
      %{name: "Runelord Brass", type_id: metallic_type.id, manufacturer_id: games_workshop.id, color: "B6A89A"},
      %{name: "Russ Grey", type_id: normal_type.id, manufacturer_id: games_workshop.id, color: "547588"},
      %{name: "Screaming Skull", type_id: normal_type.id, manufacturer_id: games_workshop.id, color: "D2D4A2"},
      %{name: "Skarsnik Green", type_id: normal_type.id, manufacturer_id: games_workshop.id, color: "5F9370"},
      %{name: "Skavenblight Dinge", type_id: normal_type.id, manufacturer_id: games_workshop.id, color: "47413B"},
      %{name: "Skrag Brown", type_id: normal_type.id, manufacturer_id: games_workshop.id, color: "90490F"},
      %{name: "Skullcrusher Brass", type_id: metallic_type.id, manufacturer_id: games_workshop.id, color: "F1C78E"},
      %{name: "Slaanesh Grey", type_id: normal_type.id, manufacturer_id: games_workshop.id, color: "8E8C97"},
      %{name: "Sotek Green", type_id: normal_type.id, manufacturer_id: games_workshop.id, color: "0B6974"},
      %{name: "Squig Orange", type_id: normal_type.id, manufacturer_id: games_workshop.id, color: "AA4F44"},
      %{name: "Stormhost Silver", type_id: metallic_type.id, manufacturer_id: games_workshop.id, color: "BBC6C9"},
      %{name: "Stormvermin Fur", type_id: normal_type.id, manufacturer_id: games_workshop.id, color: "736B65"},
      %{name: "Straken Green", type_id: normal_type.id, manufacturer_id: games_workshop.id, color: "628126"},
      %{name: "Sybarite Green", type_id: normal_type.id, manufacturer_id: games_workshop.id, color: "30A56C"},
      %{name: "Sycorax Bronze", type_id: metallic_type.id, manufacturer_id: games_workshop.id, color: "CBB394"},
      %{name: "Tallarn Sand", type_id: normal_type.id, manufacturer_id: games_workshop.id, color: "A67610"},
      %{name: "Tau Light Ochre", type_id: normal_type.id, manufacturer_id: games_workshop.id, color: "BF6E1D"},
      %{name: "Teclis Blue", type_id: normal_type.id, manufacturer_id: games_workshop.id, color: "317EC1"},
      %{name: "Temple Guard Blue", type_id: normal_type.id, manufacturer_id: games_workshop.id, color: "339A8D"},
      %{name: "Thunderhawk Blue", type_id: normal_type.id, manufacturer_id: games_workshop.id, color: "417074"},
      %{name: "Troll Slayer Orange", type_id: normal_type.id, manufacturer_id: games_workshop.id, color: "F36D2D"},
      %{name: "Tuskgor Fur", type_id: normal_type.id, manufacturer_id: games_workshop.id, color: "883636"},
      %{name: "Ulthuan Grey", type_id: normal_type.id, manufacturer_id: games_workshop.id, color: "C7E0D9"},
      %{name: "Ungor Flesh", type_id: normal_type.id, manufacturer_id: games_workshop.id, color: "D6A766"},
      %{name: "Ushabti Bone", type_id: normal_type.id, manufacturer_id: games_workshop.id, color: "BBBB7F"},
      %{name: "Warboss Green", type_id: normal_type.id, manufacturer_id: games_workshop.id, color: "3E805D"},
      %{name: "Warpfiend Grey", type_id: normal_type.id, manufacturer_id: games_workshop.id, color: "6B6A74"},
      %{name: "Warpstone Glow", type_id: normal_type.id, manufacturer_id: games_workshop.id, color: "1E7331"},
      %{name: "Wazdakka Red", type_id: normal_type.id, manufacturer_id: games_workshop.id, color: "8C0A0C"},
      %{name: "White Scar", type_id: normal_type.id, manufacturer_id: games_workshop.id, color: "FFFFFF"},
      %{name: "Wild Rider Red", type_id: normal_type.id, manufacturer_id: games_workshop.id, color: "EA2F28"},
      %{name: "Xereus Purple", type_id: normal_type.id, manufacturer_id: games_workshop.id, color: "471F5F"},
      %{name: "Yriel Yellow", type_id: normal_type.id, manufacturer_id: games_workshop.id, color: "FFDA00"},
      %{name: "Zamesi Desert", type_id: normal_type.id, manufacturer_id: games_workshop.id, color: "DDA026"},
      %{name: "Agrax Earthshade", type_id: wash_type.id, manufacturer_id: games_workshop.id, color: "5A573F"},
      %{name: "Agrax Earthshade (Gloss)", type_id: wash_type.id 	, manufacturer_id: games_workshop.id, color: "5A573F"},
      %{name: "Athonian Camoshade", type_id: wash_type.id, manufacturer_id: games_workshop.id, color: "6D8E44"},
      %{name: "Biel-Tan Green", type_id: wash_type.id, manufacturer_id: games_workshop.id, color: "1BA169"},
      %{name: "Carroburg Crimson", type_id: wash_type.id, manufacturer_id: games_workshop.id, color: "A82A70"},
      %{name: "Casandora Yellow", type_id: wash_type.id, manufacturer_id: games_workshop.id, color: "FECE5A"},
      %{name: "Coelia Greenshade", type_id: wash_type.id, manufacturer_id: games_workshop.id, color: "0E7F78"},
      %{name: "Drakenhof Nightshade", type_id: wash_type.id, manufacturer_id: games_workshop.id, color: "125899"},
      %{name: "Druchii Violet", type_id: wash_type.id, manufacturer_id: games_workshop.id, color: "7A468C"},
      %{name: "Fuegan Orange", type_id: wash_type.id, manufacturer_id: games_workshop.id, color: "C77E4D"},
      %{name: "Nuln Oil", type_id: wash_type.id, manufacturer_id: games_workshop.id, color: "14100E"},
      %{name: "Nuln Oil (Gloss)", type_id: wash_type.id 	, manufacturer_id: games_workshop.id, color: "14100E"},
      %{name: "Reikland Fleshshade", type_id: wash_type.id, manufacturer_id: games_workshop.id, color: "CA6C4D"},
      %{name: "Reikland Fleshshade (Gloss)", type_id: wash_type.id 	, manufacturer_id: games_workshop.id, color: "CA6C4D"},
      %{name: "Seraphim Sepia", type_id: wash_type.id, manufacturer_id: games_workshop.id, color: "D7824B"},
      %{name: "Astorath Red", type_id: normal_type.id, manufacturer_id: games_workshop.id, color: "DD482B"},
      %{name: "Changeling Pink", type_id: normal_type.id, manufacturer_id: games_workshop.id, color: "F4AFCD"},
      %{name: "Chronus Blue", type_id: normal_type.id, manufacturer_id: games_workshop.id, color: "72A8D1"},
      %{name: "Dawnstone", type_id: normal_type.id, manufacturer_id: games_workshop.id, color: "919C9F"},
      %{name: "Eldar Flesh", type_id: normal_type.id, manufacturer_id: games_workshop.id, color: "ECC083"},
      %{name: "Etherium Blue", type_id: normal_type.id, manufacturer_id: games_workshop.id, color: "A2BAD2"},
      %{name: "Golden Griffon", type_id: metallic_type.id, manufacturer_id: games_workshop.id, color: "A99058"},
      %{name: "Golgfag Brown", type_id: normal_type.id, manufacturer_id: games_workshop.id, color: "C2804F"},
      %{name: "Hellion Green", type_id: normal_type.id, manufacturer_id: games_workshop.id, color: "84C3AA"},
      %{name: "Hexos Palesun", type_id: normal_type.id, manufacturer_id: games_workshop.id, color: "FFF200"},
      %{name: "Hoeth Blue", type_id: normal_type.id, manufacturer_id: games_workshop.id, color: "57A9D4"},
      %{name: "Imrik Blue", type_id: normal_type.id, manufacturer_id: games_workshop.id, color: "67AED0"},
      %{name: "Kindleflame", type_id: normal_type.id, manufacturer_id: games_workshop.id, color: "F79E86"},
      %{name: "Longbeard Grey", type_id: normal_type.id, manufacturer_id: games_workshop.id, color: "CECEAF"},
      %{name: "Lucius Lilac", type_id: normal_type.id, manufacturer_id: games_workshop.id, color: "B69FCC"},
      %{name: "Necron Compound", type_id: metallic_type.id, manufacturer_id: games_workshop.id, color: "828B8E"},
      %{name: "Niblet Green", type_id: normal_type.id, manufacturer_id: games_workshop.id, color: "7DC734"},
      %{name: "Nurgling Green", type_id: normal_type.id, manufacturer_id: games_workshop.id, color: "B8CC82"},
      %{name: "Praxeti White", type_id: normal_type.id, manufacturer_id: games_workshop.id, color: "FFFFFF"},
      %{name: "Ryza Rust", type_id: normal_type.id, manufacturer_id: games_workshop.id, color: "EC631A"},
      %{name: "Sigmarite", type_id: normal_type.id, manufacturer_id: games_workshop.id, color: "CAAD76"},
      %{name: "Skink Blue", type_id: normal_type.id, manufacturer_id: games_workshop.id, color: "58C1CD"},
      %{name: "Slaanesh Grey", type_id: normal_type.id, manufacturer_id: games_workshop.id, color: "DBD5E6"},
      %{name: "Stormfang", type_id: normal_type.id, manufacturer_id: games_workshop.id, color: "80A7C1"},
      %{name: "Sylvaneth Bark", type_id: normal_type.id, manufacturer_id: games_workshop.id, color: "AC8262"},
      %{name: "Terminatus Stone", type_id: normal_type.id, manufacturer_id: games_workshop.id, color: "BDB192"},
      %{name: "Thunderhawk Blue", type_id: normal_type.id, manufacturer_id: games_workshop.id, color: "509BA9"},
      %{name: "Tyrant Skull", type_id: normal_type.id, manufacturer_id: games_workshop.id, color: "CDC586"},
      %{name: "Underhive Ash", type_id: normal_type.id, manufacturer_id: games_workshop.id, color: "C0BD81"},
      %{name: "Verminlord Hide", type_id: normal_type.id, manufacturer_id: games_workshop.id, color: "A16954"},
      %{name: "Wrack White", type_id: normal_type.id, manufacturer_id: games_workshop.id, color: "FCFBFA"},
      %{name: "Baharroth Blue", type_id: normal_type.id, manufacturer_id: games_workshop.id, color: "58C1CD"},
      %{name: "Blue Horror", type_id: normal_type.id, manufacturer_id: games_workshop.id, color: "A2BAD2"},
      %{name: "Dechala Lilac", type_id: normal_type.id, manufacturer_id: games_workshop.id, color: "B69FCC"},
      %{name: "Dorn Yellow", type_id: normal_type.id, manufacturer_id: games_workshop.id, color: "FFF200"},
      %{name: "Fulgrim Pink", type_id: normal_type.id, manufacturer_id: games_workshop.id, color: "F4AFCD"},
      %{name: "Gauss Blaster Green", type_id: normal_type.id, manufacturer_id: games_workshop.id, color: "84C3AA"},
      %{name: "Krieg Khaki", type_id: normal_type.id, manufacturer_id: games_workshop.id, color: "C0BD81"},
      %{name: "Lugganath Orange", type_id: normal_type.id, manufacturer_id: games_workshop.id, color: "F79E86"},
      %{name: "Bloodletter", type_id: wash_type.id, manufacturer_id: games_workshop.id, color: "F37355"},
      %{name: "Guilliman Blue", type_id: wash_type.id, manufacturer_id: games_workshop.id, color: "2F9AD6"},
      %{name: "Lamenters Yellow", type_id: wash_type.id, manufacturer_id: games_workshop.id, color: "FFF56B"},
      %{name: "Waywatcher Green", type_id: wash_type.id, manufacturer_id: games_workshop.id, color: "6DC066"},
      # %{name: "Agrellan Badland", type_id: texture_type.id
      # %{name: "Agrellan Earth", type_id: texture_type.id
      %{name: "Armageddon Dust", type_id: texture_type.id, manufacturer_id: games_workshop.id, color: "D3A907"},
      # %{name: "Armageddon Dunes", type_id: texture_type.id
      %{name: "Astrogranite", type_id: texture_type.id, manufacturer_id: games_workshop.id, color: "757679"},
      # %{name: "Astrogranite Debris", type_id: texture_type.id
      %{name: "Blackfire Eath", type_id: texture_type.id, manufacturer_id: games_workshop.id, color: "A75820"},
      %{name: "Lustrian Undergrowth", type_id: texture_type.id, manufacturer_id: games_workshop.id, color: "415A09"},
      # %{name: "Martian Ironcrust", type_id: texture_type.id
      # %{name: "Martian Ironearth", type_id: texture_type.id
      %{name: "Mourn Mountain Snow", type_id: texture_type.id, manufacturer_id: games_workshop.id, color: "E9EAEB"},
      # %{name: "Stirland Battlemire", type_id: texture_type.id
      %{name: "Stirland Mud", type_id: texture_type.id, manufacturer_id: games_workshop.id, color: "492B00"},
      # %{name: "Valhallan Blizzard", type_id: texture_type.id
      %{name: "'Ardcoat", type_id: technical_type.id, manufacturer_id: games_workshop.id, color: "E2DEDF"},
      %{name: "Agrellan Earth", type_id: technical_type.id, manufacturer_id: games_workshop.id, color: "9A816B"},
      %{name: "Blood for the Blood God", type_id: technical_type.id, manufacturer_id: games_workshop.id, color: "67080B"},
      %{name: "Imperial Primer", type_id: technical_type.id, manufacturer_id: games_workshop.id, color: "231F20"},
      %{name: "Lahmian Medium", type_id: technical_type.id, manufacturer_id: games_workshop.id, color: "F5EDE2"},
      %{name: "Liquid Green Stuff", type_id: technical_type.id, manufacturer_id: games_workshop.id, color: "3B7A5F"},
      %{name: "Martian Ironearth", type_id: technical_type.id, manufacturer_id: games_workshop.id, color: "C15A4B"},
      %{name: "Nihilakh Oxide", type_id: technical_type.id, manufacturer_id: games_workshop.id, color: "6CB79E"},
      %{name: "Nurgle's Rot", type_id: technical_type.id, manufacturer_id: games_workshop.id, color: "9B8F22"},
      %{name: "Soulstone Blue", type_id: technical_type.id, manufacturer_id: games_workshop.id, color: "004EFA"},
      %{name: "Spiritstone Red", type_id: technical_type.id, manufacturer_id: games_workshop.id, color: "FF4B24"},
      %{name: "Typhus Corrosion", type_id: technical_type.id, manufacturer_id: games_workshop.id, color: "463D2B"},
      %{name: "Waystone Green", type_id: technical_type.id, manufacturer_id: games_workshop.id, color: "00C000"},
    ]
    |> Enum.map(fn(%{color: string_color} = p) ->
          {:ok, byte_color} = Base.decode16(string_color)
          Map.merge(%{p | color: byte_color}, %{inserted_at: DateTime.utc_now, updated_at: DateTime.utc_now}) end)
    |> IO.inspect

    PaintSchemer.Repo.insert_all(Paint, paints)
  end
end
